print("==================================")
print("= NAMA    : LYDIA DIFFANI SIREGAR ")
print("= NIM     : 312010498             ")
print("= KELAS   : TI.20 A.1             ")
print("==================================")

print("Please enter your full name : LYDIA DIFFANI SIREGAR ")
fullname=input()
print("Please enter nickname : LYDIA")
nickname=input()
print("Please enter your NPM : 312010498")
npm=input()
print("Please enter place of birth : BEKASI")
pob=input()
print("Please enter date of birth : 09 ")
date=input()
print("Please enter your month of birth : APRIL")
month=input()
print("Please enter year of birth : 2001")
year=input()
print("Please enter your phone number : 088290260648")
phone=input()
print("Please enter your address : Kp.Kandang")
address=input()

dob=input("2020-year")

print("\n\n Assalamu'alaikum.")
print("Let me introduce my self, my name is {LYDIA DIFFANI SIREGAR}, but you can call me {LYDIA}, my NPM {312010498}, I was born in {BEKASI} and iam {19} years old, I am very glad if you want to invite my house in {Kp.Kandang}, So don't forget to call me before with the number {088290260648}, \n\n Thanks you ")